site_name: RDS
site_url: https://ecstatic5.github.io/luau-data-structures/
repo_url: https://github.com/ecstatic5/luau-data-structures
repo_name: luau-data-structures

nav:
  - Home: index.md
  - About: about.md
  - Tutorial:
    - Installation: tutorial/installation.md
    - Creating a data structure: tutorial/creating-data-structure.md
  - API:
    - Data Structures: api/data-structures.md
    - Array: api/arrays.md
    - Types: api/types.md
  - Changelog: changelog.md
theme:
    name: material
    features:
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
    language: en
    palette:
        - scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
          primary: teal
          accent: purple
        - scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
          primary: teal
          accent: lime

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
          generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: © 2023 <a href="https://github.com/ecstatic5/luau-data-structures" target="_blank" rel="noopener"> ecstatic5 & iiAngel